export default {
  colors: {
    background: '#121212',
    primary: '#2a2e52',
    secondary: '#25284a',
    border: 'rgba(255, 255, 255, 0.1)',
    borderSelected: 'rgba(50, 197, 255, 0.5)',
    text: '#fff',
    buttonText: '#fff',
    buttonDisabled: '#363154',
    icon: '#bbb',
    placeholder: '#bbb',
    inputBackground: '#313354',
    secondaryBackground: '#272b4f',
    nextButtonBackground: '#363154',
    nextButtonBorder: [
      "rgba(255, 193, 7, 0.5)",
      "rgba(182, 32, 224, 0.5)",
      "rgba(50, 197, 255, 0.5)"
    ]
  },
  spacing: {
    padding: 20,
    margin: 10,
    verticalMargin: 20,
    inputPadding: 2,
    containerPadding: 10,
  },
  borderRadius: 16,
  container: {
    flex: 1,
    justifyContent: "space-between",
    padding: 20,
    backgroundColor: "transparent",
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 10,
    alignSelf: 'center',
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '400',
    marginBottom: 20,
    alignSelf: 'center',
    textAlign: 'center',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 20,
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingBottom: 40,
    paddingHorizontal: 10,
  },
  input: {
    flex: 1,
    color: '#fff',
    marginLeft: 8,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#313354',
    padding: 2,
    borderRadius: 8,
    marginTop: 10,
  },
};
