export default {
  colors: {
    background: '#121212',
    primary: '#6200EA',
    secondary: '#222',
    text: '#fff',
    buttonText: '#fff',
    buttonDisabled: '#444',
    selected: '#555',
    icon: '#bbb',
    placeholder: '#bbb',
    inputBackground: '#333',
    secondaryBackground: '#222',
  },
  spacing: {
    padding: 20,
    margin: 10,
    verticalMargin: 20,
    inputPadding: 2,
    containerPadding: 10,
  },
  borderRadius: 15,
  container: {
    flex: 1,
    justifyContent: 'space-between',
    padding: 20,
    backgroundColor: '#121212',
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 10,
    alignSelf: 'center',
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 14,
    color: '#bbb',
    marginBottom: 20,
    alignSelf: 'center',
    textAlign: 'center',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 20,
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingBottom: 40,
    paddingHorizontal: 10,
  },
  input: {
    flex: 1,
    color: '#fff',
    marginLeft: 10,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#333',
    padding: 4,
    borderRadius: 8,
    marginTop: 5,
  },
};
